POST http://localhost:9000/api/auth/register
Content-Type: application/json

{
    "username": "Alex",
    "password": "1234"
}

####

POST http://localhost:9000/api/auth/login
Content-Type: application/json

{
    "username": "Alex",
    "password": "1234"
}

####

GET http://localhost:9000/api/auth/logout

####

GET http://localhost:9000/api/users
# Cookie: chocolatechip= 
# this was suppose to delete the cookie, but it didn't work so I just tested it in Postman

####

GET http://localhost:9000/